/**
 * Google Gemini Multimodal Vision API Client
 * Uses gemini-2.0-flash to analyze food images and extract detailed nutrition.
 */

export async function analyzeFoodWithGemini({ imageBase64, mimeType = 'image/jpeg', apiKey, userGoal = 'loss_moderate', customNotes = '' }) {
  if (!apiKey) {
    throw new Error('Gemini API key is required. Please set it in Settings or use the smart simulator.');
  }

  // Sanitize base64 string
  const cleanBase64 = imageBase64.replace(/^data:image\/[a-z]+;base64,/, '');

  const prompt = `You are a world-class AI Clinical Nutritionist and Computer Vision Food Specialist.
Analyze the provided food photograph in detail.

User's current fitness goal: "${userGoal}" (e.g. fat loss, lean muscle gain, maintenance).
User's additional context: "${customNotes || 'None'}".

Identify every individual food item/ingredient visible on the plate, estimate its portion size in grams, and calculate precise macronutrients and calories.

Return ONLY a valid JSON object matching this exact schema:
{
  "mealName": "Short descriptive name of the dish (e.g., Grilled Herb Chicken with Quinoa and Roasted Asparagus)",
  "confidenceScore": 0.95,
  "healthScore": 8.5,
  "tags": ["High Protein", "Low Glycemic", "Heart Healthy", "Gluten-Free"],
  "totalNutrition": {
    "calories": 540,
    "protein": 46,
    "carbs": 42,
    "fat": 16,
    "fiber": 8,
    "sugar": 4,
    "sodiumMg": 420
  },
  "items": [
    {
      "name": "Grilled Chicken Breast",
      "portionGrams": 180,
      "calories": 290,
      "protein": 38,
      "carbs": 0,
      "fat": 4,
      "fiber": 0
    },
    {
      "name": "Steamed Quinoa",
      "portionGrams": 120,
      "calories": 145,
      "protein": 5,
      "carbs": 26,
      "fat": 2.5,
      "fiber": 3.5
    },
    {
      "name": "Roasted Asparagus with Olive Oil",
      "portionGrams": 80,
      "calories": 105,
      "protein": 3,
      "carbs": 4,
      "fat": 9.5,
      "fiber": 4.5
    }
  ],
  "coachInsight": "Actionable 2-sentence nutritional advice tailored to their '${userGoal}' goal.",
  "volumeSatietyScore": "High"
}

Important:
- Provide realistic estimates based on standard culinary serving sizes.
- Respond with pure JSON only, without markdown code fences or backticks.`;

  const url = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=${apiKey}`;

  const requestBody = {
    contents: [
      {
        parts: [
          { text: prompt },
          {
            inline_data: {
              mime_type: mimeType,
              data: cleanBase64
            }
          }
        ]
      }
    ],
    generationConfig: {
      temperature: 0.2,
      response_mime_type: 'application/json'
    }
  };

  const response = await fetch(url, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json'
    },
    body: JSON.stringify(requestBody)
  });

  if (!response.ok) {
    const errorData = await response.json().catch(() => ({}));
    throw new Error(errorData.error?.message || `Gemini API request failed with status ${response.status}`);
  }

  const data = await response.json();
  const rawText = data.candidates?.[0]?.content?.parts?.[0]?.text;

  if (!rawText) {
    throw new Error('No nutrition response generated by Gemini AI.');
  }

  try {
    // Clean potential markdown if returned
    const cleanJson = rawText.replace(/```json/gi, '').replace(/```/g, '').trim();
    return JSON.parse(cleanJson);
  } catch (err) {
    console.error('Failed to parse Gemini JSON output:', rawText);
    throw new Error('Could not parse nutrition data format from AI response.');
  }
}
